# .air.toml
root = "/app"
tmp_dir = "/app/tmp"

[build]
  bin = "/app/tmp/main"
  cmd = "go build -o /app/tmp/main ./server/cmd/main.go"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "scripts", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "js", "css", "json", "yaml", "yml", "md"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = "gold"
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
